### ISSUE TITLE
Remote file (URL): No files were found with a gml or xml file extension

### ISSUE THREAD

**Issue by juremekis** [interactive-instruments/etf-webapp#146]
I'm using the INSPIRE validator to validate metadata, using [this](http://prostor4.gov.si/imps/srv/slv/xml.metadata.get?uuid=3e0b727e-49d5-4c7f-835b-823c5392a307) URL as Data source. The app gives me the following error:
>Test run initialization failure: No files were found with a gml or xml file extension!

![slika](https://user-images.githubusercontent.com/18478668/33886044-90b77afc-df45-11e7-8d91-1605480494f0.png)

The etf-webapp should check the remote URL's `Content-Type` HTTP header for XML /GML content instead of just checking for an appropriate extension.

In my case, the header is  `Content-Type:application/xml;charset=UTF-8`, which should be accepted as a valid remote URL.

**Comment by jonherrmann** [comment]
Thanks for reporting this issue.

The Validator first uses the Content-Disposition Header than searches for an ending in the URL and afterwards uses the Content-Type header. This is done because many services just return inappropriate  Content-Type headers like ```text/plain``` for a XML file.

In your case ```.get``` is found as file ending. The mechanism has to be changed.
