### ISSUE TITLE
Schematron: XSLT2 error 

### ISSUE THREAD

**Issue by thijsbrentjens** [interactive-instruments/etf-webapp#17]
For a Schematron test we need XSLT2 support. I added the attached file to use, but this resulted in the error:

Fail: This implementation of ISO Schematron does not work with 
	schemas using the "xslt2" query language.

Do I need to change something in the test?

[schematron.sch.txt](https://github.com/interactive-instruments/etf-webapp/files/261299/schematron.sch.txt)

**Comment by jechterhoff** [comment]
Hello Thijs,

The Schematron test project is probably still using the Schematron reference implementation that is based on XSLT 1.0. The according files are contained in the folder named iso-schematron-xslt1.

I just tried an upgrade to the XSLT2 reference implementation. To modify your testproject, follow these instructions:

1. Download the file http://www.schematron.com/tmp/iso-schematron-xslt2.zip and extract it to a new folder called 'iso-schematron-xslt2' (parallel to the 'iso-schematron-xslt1' folder) in your testproject.
2. Copy all files from 'iso-schematron-xslt1' that have the prefix 'ii_' to 'iso-schematron-xslt2'.
3. Open Schematron-basex.xq and apply the following edits:
3.1 Replace all occurrences of 'iso-schematron-xslt1' with 'iso-schematron-xslt2'
3.2 Replace the occurrence of 'iso_svrl_for_xslt1.xsl' with 'iso_svrl_for_xslt2.xsl'

We could update the naming in the Schematron testproject so that the XSLT implementation can more easily be changed. Right now, this is the quickest way to update your test project.

When I tested this, it worked when I had Saxon 9 on the classpath. However, note that a Schematron testproject that uses the regex implementation (namespace: nl.vrom.roo.util.Regexp) will not work. The reason is that this requires execution by Xalan (BaseX uses Saxon to execute XSLT if it finds it on the classpath).

Best regards,
Johannes

**Comment by jonherrmann** [comment]
Saxon supports the matches function.

In order to get the schematron test projects -which use the regex:matches function- work again, you could delete this line in the corresponding schematron files:
```
<iso:ns prefix="regexp" uri="nl.vrom.roo.util.Regexp"/>
```

and replace
```
regex:matches(
```
calls with
```
matches(
```

**Comment by thijsbrentjens** [comment]
Hello Johannes, Jon, thanks for the help and quick reply. I'm travelling now, so can't test it rigth now, sorry. But we'll manage with this information.

**Comment by jonherrmann** [comment]
reopen if necessary
