### ISSUE TITLE
Schematron validation is not executed if XML validation fails

### ISSUE THREAD

**Issue by thijsbrentjens** [interactive-instruments/etf-webapp#18]
It seems that Schematron validation is not exectued if XML validation fails. Is this by design? 

Is there a way to force Schematron validation to always run, also if XML validation fails?

**Comment by jonherrmann** [comment]
Its by design: not schema valid files are excluded from the tests. It is the basic check for verifying that the uploaded data are in a specific format and also ensures that the executed tests do not result in unexpected behavior or fault masking.

We could add a switch for that, but then you may need to change the implemented tests to expect or catch errors which were caught by the schema validation before.

Example: the application schema allows a feature to posses one 'property' property and there is an implemented xpath test wich checks that property has always the value 'value': /collection/feature[1]/property = 'value' . A user that uploads a feature instance, in a collection, with two 'propery'-properties, will fail the whole test run (without a created test report).

**Comment by thijsbrentjens** [comment]
Okay, good to know, thanks @jonherrmann for your quick reply. I'm going to analyse impact on our tests with some colleagues.
