### ISSUE TITLE
SUI: Handle non-text/xml content-type header responses

### ISSUE THREAD

**Issue by jonherrmann** [interactive-instruments/etf-webapp#63]

**Comment by cportele** [comment]
Regarding the original issue in #17: 

WFS, like the OGC Web Service standards in general, do not state explicit requirements related to the "Content-Type" header of responses. Arguably this is a shortcoming, but one that is there.

Since HTTP 1.1 is a normative reference (of all OGC Web Service standards), the rules related to the Content-Type header from HTTP 1.1 (RFC 2616) apply: "The Content-Type entity-header field indicates the media type of the entity-body sent to the recipient ..." (section 14.17). Note that including the header is recommended by HTTP 1.1, but not required.

So, _if_ a Content-Type header is provided, it has to be consistent with the content. Since no media type exists for XML Schema, the Content-Type in a DescribeFeatureType response with an XML Schema document should be 'application/xml' or 'text/xml' (see RFC 3023).

To explain why an implementer might return 'application/gml+xml; version=3.2' in a DescribeFeatureType response: The approach in the WFS standard has been to use a request parameter outputFormat to control the output, in this case the type of schema:

"In response to a DescribeFeatureType request, where the value of the outputFormat parameter has been set to [the default value] 'application/gml+xml; version=3.2', a WFS implementation shall return a complete and valid GML (see ISO 19136:2007) application schema that contains the definition of the feature types listed in the request." - http://docs.opengeospatial.org/is/09-025r2/09-025r2.html#151

'application/gml+xml; version=3.2' is clearly not the media type of an XML Schema document (and therefore incorrect in the Content-Type header), but it is easy to see why an implementer could get the idea from the standard to use the media type also in the "Content-Type" header. I.e. all cases that are not 'application/xml' or 'text/xml' should be detected and reported (with reference to RFCs 2616 and 3023).

**Comment by jonherrmann** [comment]
Update after further investigation by MML: Bug in etf or soapui?

> I added a Servlet Filter to modify the content type of the responses for DescribeFeatureType requests.
Now both of these return with the correct Content-Type: text/xml;charset=UTF-8
 https://wfs?service=wfs&version=2.0.0&request=DescribeFeatureType&outputFormat=text/xml;%20subtype=gml/3.2.1
https://wfs?service=wfs&version=2.0.0&request=DescribeFeatureType&outputFormat=application/gml+xml;%20version=3.2
However, the validator still fails on Auto-Configure (still the same error):
http://elf-validator/etf-webapp/reports/787f55e2-0e1f-417c-80a6-0c334377db4a

**Comment by jonherrmann** [comment]
can't be reproduced in version 2.0.0 with SoapUI 5.3.0
