### ISSUE TITLE
Support for large GML files (from survey)

### ISSUE THREAD

**Issue by lorenahq** [interactive-instruments/etf-webapp#89]
Some users need support for larger GML files. In particular, someone tried with a file of  840'000KB but the validator ended up crashing.

**Comment by jonherrmann** [comment]
1. crash should be avoided if possible (bug)
2. The upload size should be adjusted to RAM (enhancement)

**Comment by cportele** [comment]
As a note, the crash occurs, because the current test deployment is on a machine that does not have sufficient RAM for executing the xqueries on files of that size. However, the software is capable of handling very large files (and has been used with XML files of more than 200GB), but the machine needs to have sufficient RAM.
